[package]
name = "masto-snowflake-to-uuid7"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.96"
time = "0.3.21"
uuid = { version = "1.3.2", features = ["v7"] }
uuid7 = { version = "0.6.2", features = ["uuid"] }
wyrand = "0.1.1"
